#!/bin/bash

# Clean Template Insertion Script
# Server: 195.35.45.17
# Database: kivi

echo "🚀 Starting clean insertion of assessment templates..."

# Server credentials
SERVER="195.35.45.17"
USER="root"
PASSWORD="Tiger@123"
DATABASE="kivi"

# Function to execute SQL with better error handling
execute_sql() {
    local sql="$1"
    echo "Inserting: $(echo "$sql" | grep -o "'[^']*'" | head -1 | tr -d "'")"
    sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USER@$SERVER" "mysql -u $USER -p$PASSWORD $DATABASE -e \"$sql\"" 2>/dev/null
    if [ $? -eq 0 ]; then
        echo "✅ Success"
    else
        echo "❌ Failed"
    fi
    echo ""
}

# Insert templates one by one with proper escaping
echo "📋 Inserting assessment templates..."

# 1. ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-PRIMARY
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-PRIMARY', 'RIPA-Primary', 'Cognitive', 'The RIPA-A quantifies & describes cognitive-linguistic deficits in individuals between the ages of 5-0 and 12-11 who face difficulties in attention, memory, orientation, language and communication, problem solving and abstract reasoning.', '🧠', '{\"id\": \"RIPA-Primary\", \"name\": \"ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-PRIMARY\", \"description\": \"The RIPA-A quantifies & describes cognitive-linguistic deficits in individuals between the ages of 5-0 and 12-11 who face difficulties in attention, memory, orientation, language and communication, problem solving and abstract reasoning.\", \"category\": \"Cognitive\", \"icon\": \"🧠\", \"subtests\": [\"Attention\", \"Memory\", \"Orientation\", \"Language\", \"Communication\", \"Problem Solving\", \"Abstract Reasoning\"]}', '{\"compositeScore\": {\"formula\": \"SUM(subtest_scores) / COUNT(subtest_scores)\"}}', '{\"ageNorms\": true, \"standardScores\": true}', '5-12 years', '[\"English\", \"Hindi\"]', 'active', 1, 1);"

# 2. ADHD-DSM5 Checklist
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('ADHD-DSM5 Checklist', 'ADHT-BSM', 'ADHD', 'DSM-5 ADHD Checklist with checkbox-based criteria selection for inattention and hyperactivity', '📋', '{\"id\": \"ADHT-BSM\", \"name\": \"ADHD-DSM5 Checklist\", \"description\": \"DSM-5 ADHD Checklist with checkbox-based criteria selection for inattention and hyperactivity\", \"category\": \"ADHD\", \"icon\": \"📋\", \"sections\": [{\"name\": \"Inattention\", \"criteria\": [\"Often fails to give close attention to details\", \"Often has difficulty sustaining attention\"], \"requiredForDiagnosis\": 6}]}', '{\"inattentionScore\": {\"formula\": \"COUNT(criteria_checked)\", \"max\": 9}}', '{\"diagnosticCriteria\": true}', '4-18 years', '[\"English\", \"Hindi\"]', 'active', 1, 2);"

# 3. Aston Index Assessment
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Aston Index Assessment', 'Aston-Index', 'Educational', 'The Aston Index procedures are designed to be used by class teachers, psychologists, and others who wish to identify children with special educational needs.', '📚', '{\"id\": \"Aston-Index\", \"name\": \"Aston Index Assessment\", \"description\": \"The Aston Index procedures are designed to be used by class teachers, psychologists, and others who wish to identify children with special educational needs.\", \"category\": \"Educational\", \"icon\": \"📚\", \"subtests\": [\"Visual Perception\", \"Auditory Perception\", \"Motor Skills\"]}', '{\"totalScore\": {\"formula\": \"SUM(subtest_scores)\", \"max\": 100}}', '{\"ageNorms\": true}', '5-16 years', '[\"English\"]', 'active', 1, 3);"

# 4. WRAT5-India Blue Form
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WRAT5-India Blue Form', 'WRAT5', 'Academic', 'Wide Range Achievement Test 5 - India Blue Form for assessing reading, spelling, and math skills', '✏️', '{\"id\": \"WRAT5\", \"name\": \"WRAT5-India Blue Form\", \"description\": \"Wide Range Achievement Test 5 - India Blue Form for assessing reading, spelling, and math skills\", \"category\": \"Academic\", \"icon\": \"✏️\", \"subtests\": [\"Word Reading\", \"Sentence Comprehension\", \"Spelling\", \"Math Computation\"]}', '{\"readingRaw\": {\"formula\": \"SUM(correct_answers)\", \"max\": 55}}', '{\"standardScores\": true}', '5-94 years', '[\"English\"]', 'active', 1, 4);"

# 5. EACA AUTISM ASSESSMENT
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('EACA AUTISM ASSESSMENT', 'ADHDT2', 'ADHD', 'Attention-Deficit/Hyperactivity Disorder Test-Second Edition with comprehensive scoring', '📝', '{\"id\": \"ADHDT2\", \"name\": \"EACA AUTISM ASSESSMENT\", \"description\": \"Attention-Deficit/Hyperactivity Disorder Test-Second Edition with comprehensive scoring\", \"category\": \"ADHD\", \"icon\": \"📝\"}', '{\"adhdIndex\": {\"formula\": \"(inattentionScore + hyperactivityScore) / 2\"}}', '{\"comprehensiveScoring\": true}', '6-18 years', '[\"English\"]', 'active', 1, 5);"

# 6. Bender Gestalt Test (BKT)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Bender Gestalt Test (BKT)', 'BKT', 'Motor', 'Motor coordination and kinesthetic perception assessment', '✏️', '{\"id\": \"BKT\", \"name\": \"Bender Gestalt Test (BKT)\", \"description\": \"Motor coordination and kinesthetic perception assessment\", \"category\": \"Motor\", \"icon\": \"✏️\", \"figures\": 9}', '{\"motorScore\": {\"formula\": \"SUM(accuracy_scores)\"}}', '{\"motorCoordination\": true}', '5-11 years', '[\"English\"]', 'active', 1, 6);"

# 7. Raven's Coloured Progressive Matrices
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Raven\\'s Coloured Progressive Matrices', 'Ravens-CPM', 'Cognitive', 'Non-verbal assessment of eductive ability and problem-solving skills', '🧩', '{\"id\": \"Ravens-CPM\", \"name\": \"Raven\\'s Coloured Progressive Matrices\", \"description\": \"Non-verbal assessment of eductive ability and problem-solving skills\", \"category\": \"Cognitive\", \"icon\": \"🧩\", \"sets\": [\"A\", \"Ab\", \"B\", \"C\", \"D\", \"E\"], \"itemsPerSet\": 12}', '{\"educativeAbility\": {\"formula\": \"SUM(correct_answers)\", \"max\": 36}}', '{\"nonVerbalReasoning\": true}', '5-11 years', '[\"English\"]', 'active', 1, 7);"

# 8. Gilliam Autism Rating Scale - 3
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Gilliam Autism Rating Scale - 3', 'GARS-3', 'Autism', 'Comprehensive assessment tool for identifying autism spectrum disorders', '🧩', '{\"id\": \"GARS-3\", \"name\": \"Gilliam Autism Rating Scale - 3\", \"description\": \"Comprehensive assessment tool for identifying autism spectrum disorders\", \"category\": \"Autism\", \"icon\": \"🧩\", \"subscales\": [\"Stereotyped Behaviors\", \"Communication\", \"Social Interaction\"]}', '{\"autismIndex\": {\"formula\": \"SUM(subscale_scores)\"}}', '{\"autismAssessment\": true}', '3-22 years', '[\"English\"]', 'active', 1, 8);"

# 9. Brown Executive Function/Attention Scales
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Brown Executive Function/Attention Scales', 'Brown-EF-A', 'Executive', 'Comprehensive assessment of executive function and attention processes', '🧠', '{\"id\": \"Brown-EF-A\", \"name\": \"Brown Executive Function/Attention Scales\", \"description\": \"Comprehensive assessment of executive function and attention processes\", \"category\": \"Executive\", \"icon\": \"🧠\", \"clusters\": [\"Activation\", \"Focus\", \"Effort\", \"Emotion\", \"Memory\", \"Action\"]}', '{\"executiveFunctionIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"executiveFunction\": true}', '3-18 years', '[\"English\"]', 'active', 1, 9);"

# 10. Early Academic Competency Assessment
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Early Academic Competency Assessment', 'EACA', 'Academic', 'Comprehensive screening tool for early academic skills and school readiness', '📚', '{\"id\": \"EACA\", \"name\": \"Early Academic Competency Assessment\", \"description\": \"Comprehensive screening tool for early academic skills and school readiness\", \"category\": \"Academic\", \"icon\": \"📚\", \"domains\": [\"Pre-Reading\", \"Pre-Writing\", \"Mathematics\", \"Language\", \"Social Skills\"]}', '{\"readinessIndex\": {\"formula\": \"SUM(domain_scores)\"}}', '{\"schoolReadiness\": true}', '4-6 years', '[\"English\"]', 'active', 1, 10);"

# 11. Educational Assessment of Children with Autism (EACA)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Educational Assessment of Children with Autism (EACA)', 'EACA-Autism', 'Autism', 'Comprehensive assessment of children with autism focusing on the triad of impairments across 7 domains', '🧩', '{\"id\": \"EACA-Autism\", \"name\": \"Educational Assessment of Children with Autism (EACA)\", \"description\": \"Comprehensive assessment of children with autism focusing on the triad of impairments across 7 domains\", \"category\": \"Autism\", \"icon\": \"🧩\", \"domains\": [\"Social Interaction\", \"Communication\", \"Imagination\", \"Behavior\", \"Cognition\", \"Sensory\", \"Motor\"]}', '{\"autismSeverity\": {\"formula\": \"SUM(domain_scores)\"}}', '{\"autismAssessment\": true}', '3-18 years', '[\"English\"]', 'active', 1, 11);"

# 12. Nelson-Denny Reading Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Nelson-Denny Reading Test', 'Nelson-Denny', 'Reading', 'Comprehensive assessment of reading comprehension, vocabulary, and reading rate', '📖', '{\"id\": \"Nelson-Denny\", \"name\": \"Nelson-Denny Reading Test\", \"description\": \"Comprehensive assessment of reading comprehension, vocabulary, and reading rate\", \"category\": \"Reading\", \"icon\": \"📖\", \"subtests\": [\"Vocabulary\", \"Comprehension\", \"Reading Rate\"]}', '{\"readingIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"readingAssessment\": true}', '9-18 years', '[\"English\"]', 'active', 1, 12);"

# 13. TEST OF AUDITORY PROCESSING SKILLS-TAPS-3
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('TEST OF AUDITORY PROCESSING SKILLS-TAPS-3', 'TAPS-3', 'Auditory', 'Comprehensive auditory processing assessment for phonological skills, memory abilities, and auditory cohesion', '👂', '{\"id\": \"TAPS-3\", \"name\": \"TEST OF AUDITORY PROCESSING SKILLS-TAPS-3\", \"description\": \"Comprehensive auditory processing assessment for phonological skills, memory abilities, and auditory cohesion\", \"category\": \"Auditory\", \"icon\": \"👂\", \"subtests\": [\"Phonological Awareness\", \"Phonemic Awareness\", \"Memory\", \"Cohesion\"]}', '{\"auditoryProcessingIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"auditoryProcessing\": true}', '4-18 years', '[\"English\"]', 'active', 1, 13);"

# 14. TEST OF WRITTEN LANGUAGE (TOWL-4)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('TEST OF WRITTEN LANGUAGE (TOWL-4)', 'TOWL-4', 'Writing', 'The TOWL-4 is a norm-referenced, reliable, and valid test of written language measuring seven skill areas and three composite scores.', '✍️', '{\"id\": \"TOWL-4\", \"name\": \"TEST OF WRITTEN LANGUAGE (TOWL-4)\", \"description\": \"The TOWL-4 is a norm-referenced, reliable, and valid test of written language measuring seven skill areas and three composite scores.\", \"category\": \"Writing\", \"icon\": \"✍️\", \"subtests\": [\"Vocabulary\", \"Spelling\", \"Punctuation\", \"Logical Sentences\"]}', '{\"writtenLanguageIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"writingAssessment\": true}', '9-18 years', '[\"English\"]', 'active', 1, 14);"

# 15. VINELAND ADAPTIVE BEHAVIOUR SCALES-VABS-3
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('VINELAND ADAPTIVE BEHAVIOUR SCALES-VABS-3', 'VABS-3', 'Behavior', 'Individual assessment of adaptive behaviour measuring day-to-day activities necessary for self-care and social interaction.', '👥', '{\"id\": \"VABS-3\", \"name\": \"VINELAND ADAPTIVE BEHAVIOUR SCALES-VABS-3\", \"description\": \"Individual assessment of adaptive behaviour measuring day-to-day activities necessary for self-care and social interaction.\", \"category\": \"Behavior\", \"icon\": \"👥\", \"domains\": [\"Communication\", \"Daily Living Skills\", \"Socialization\", \"Motor Skills\"]}', '{\"adaptiveBehaviorIndex\": {\"formula\": \"SUM(domain_scores)\"}}', '{\"adaptiveBehavior\": true}', '0-90 years', '[\"English\"]', 'active', 1, 15);"

# 16. WECHSLER'S INTELLIGENCE SCALE FOR CHILDREN -WISC-IV India
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WECHSLER\\'S INTELLIGENCE SCALE FOR CHILDREN -WISC-IV India', 'WISC-4', 'Intelligence', 'Norm-referenced, individually administered test of intelligence for children with verbal and performance subtests.', '🧠', '{\"id\": \"WISC-4\", \"name\": \"WECHSLER\\'S INTELLIGENCE SCALE FOR CHILDREN -WISC-IV India\", \"description\": \"Norm-referenced, individually administered test of intelligence for children with verbal and performance subtests.\", \"category\": \"Intelligence\", \"icon\": \"🧠\", \"subtests\": [\"Similarities\", \"Vocabulary\", \"Comprehension\", \"Information\", \"Digit Span\"]}', '{\"verbalComprehension\": {\"formula\": \"SUM(verbal_subtests) / 5\"}}', '{\"intelligenceAssessment\": true}', '6-16 years', '[\"English\"]', 'active', 1, 16);"

# 17. WJ-III - TESTS OF ACHIEVEMENT FORM C/ BRIEF BATTERY
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WJ-III - TESTS OF ACHIEVEMENT FORM C/ BRIEF BATTERY', 'WJ-3', 'Achievement', 'Norm-referenced individually administered tests measuring academic achievement across reading, math, and writing.', '📊', '{\"id\": \"WJ-3\", \"name\": \"WJ-III - TESTS OF ACHIEVEMENT FORM C/ BRIEF BATTERY\", \"description\": \"Norm-referenced individually administered tests measuring academic achievement across reading, math, and writing.\", \"category\": \"Achievement\", \"icon\": \"📊\", \"clusters\": [\"Broad Reading\", \"Broad Math\", \"Broad Written Language\"]}', '{\"achievementIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"academicAchievement\": true}', '2-90 years', '[\"English\"]', 'active', 1, 17);"

# 18. WOODCOCK-JOHNSON TESTS OF COGNITIVE ABILITIES IV (WJ-Cog)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WOODCOCK-JOHNSON TESTS OF COGNITIVE ABILITIES IV (WJ-Cog)', 'WJ-Cog', 'Cognitive', '18 tests measuring different aspects of cognitive ability based on CHC theory, with cluster scores for interpretative purposes.', '🧠', '{\"id\": \"WJ-Cog\", \"name\": \"WOODCOCK-JOHNSON TESTS OF COGNITIVE ABILITIES IV (WJ-Cog)\", \"description\": \"18 tests measuring different aspects of cognitive ability based on CHC theory, with cluster scores for interpretative purposes.\", \"category\": \"Cognitive\", \"icon\": \"🧠\", \"clusters\": [\"Comprehension-Knowledge\", \"Long-Term Retrieval\", \"Visual-Spatial Thinking\"]}', '{\"cognitiveIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"cognitiveAbilities\": true}', '2-90 years', '[\"English\"]', 'active', 1, 18);"

# 19. WOODCOCK JOHNSON IV TESTS OF ACHIEVEMENT (WJ-Ach)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WOODCOCK JOHNSON IV TESTS OF ACHIEVEMENT (WJ-Ach)', 'WJ-Ach', 'Achievement', 'Comprehensive set of individually administered tests to measure educational achievement in reading, mathematics, written language, and academic skills.', '📚', '{\"id\": \"WJ-Ach\", \"name\": \"WOODCOCK JOHNSON IV TESTS OF ACHIEVEMENT (WJ-Ach)\", \"description\": \"Comprehensive set of individually administered tests to measure educational achievement in reading, mathematics, written language, and academic skills.\", \"category\": \"Achievement\", \"icon\": \"📚\", \"clusters\": [\"Basic Reading Skills\", \"Reading Comprehension\", \"Broad Reading\"]}', '{\"achievementIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"academicAchievement\": true}', '2-90 years', '[\"English\"]', 'active', 1, 19);"

# 20. WIDE RANGE ACHIEVEMENT TEST- WRAT-5 (ENGLISH)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WIDE RANGE ACHIEVEMENT TEST- WRAT-5 (ENGLISH)', 'WRAT5', 'Achievement', 'Norm-referenced test measuring basic academic skills of word reading, sentence comprehension, spelling, and math computation.', '📝', '{\"id\": \"WRAT5\", \"name\": \"WIDE RANGE ACHIEVEMENT TEST- WRAT-5 (ENGLISH)\", \"description\": \"Norm-referenced test measuring basic academic skills of word reading, sentence comprehension, spelling, and math computation.\", \"category\": \"Achievement\", \"icon\": \"📝\", \"subtests\": [\"Word Reading\", \"Sentence Comprehension\", \"Spelling\", \"Math Computation\"]}', '{\"basicSkillsIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"basicAcademicSkills\": true}', '5-94 years', '[\"English\"]', 'active', 1, 20);"

# 21. WOODCOCK READING MASTERY TESTS-II (WRMT-II)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WOODCOCK READING MASTERY TESTS-II (WRMT-II)', 'WRMT2', 'Reading', 'Individually administered, timed tests measuring Basic Skills, Reading Comprehension, Oral Reading Fluency and Listening Comprehension.', '📖', '{\"id\": \"WRMT2\", \"name\": \"WOODCOCK READING MASTERY TESTS-II (WRMT-II)\", \"description\": \"Individually administered, timed tests measuring Basic Skills, Reading Comprehension, Oral Reading Fluency and Listening Comprehension.\", \"category\": \"Reading\", \"icon\": \"📖\", \"subtests\": [\"Visual-Auditory Learning\", \"Letter Identification\", \"Word Identification\"]}', '{\"readingMasteryIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"readingMastery\": true}', '5-75 years', '[\"English\"]', 'active', 1, 21);"

# 22. DIAGNOSTIC ASSESSMENT REPORT
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('DIAGNOSTIC ASSESSMENT REPORT', 'DiagnosticReport', 'Diagnostic', 'Comprehensive diagnostic assessment report based on DSM-5 criteria and standardized test results.', '🧠', '{\"id\": \"DiagnosticReport\", \"name\": \"DIAGNOSTIC ASSESSMENT REPORT\", \"description\": \"Comprehensive diagnostic assessment report based on DSM-5 criteria and standardized test results.\", \"category\": \"Diagnostic\", \"icon\": \"🧠\", \"sections\": [\"Client Information\", \"Background History\", \"Assessment Results\"]}', '{\"diagnosticSummary\": {\"formula\": \"CONCATENATE(assessment_results, diagnostic_impressions)\"}}', '{\"diagnosticReport\": true}', 'All ages', '[\"English\"]', 'active', 1, 22);"

# 23. SUMMARY OF EVALUATION
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('SUMMARY OF EVALUATION', 'EvaluationSummary', 'Summary', 'Comprehensive summary of evaluation results across multiple assessment instruments including WJ-IV COG, WJ-IV ACH, and Brown\\'s EF/A Scale.', '📊', '{\"id\": \"EvaluationSummary\", \"name\": \"SUMMARY OF EVALUATION\", \"description\": \"Comprehensive summary of evaluation results across multiple assessment instruments including WJ-IV COG, WJ-IV ACH, and Brown\\'s EF/A Scale.\", \"category\": \"Summary\", \"icon\": \"📊\", \"instruments\": [\"WJ-IV COG\", \"WJ-IV ACH\", \"Brown EF/A Scale\"]}', '{\"evaluationSummary\": {\"formula\": \"AGGREGATE(instrument_results)\"}}', '{\"comprehensiveSummary\": true}', 'All ages', '[\"English\"]', 'active', 1, 23);"

echo "✅ Template insertion completed!"
echo "📊 Checking final results..."

# Show summary
sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USER@$SERVER" "mysql -u $USER -p$PASSWORD $DATABASE -e \"SELECT COUNT(*) as total_templates, COUNT(CASE WHEN is_active = 1 THEN 1 END) as active_templates, GROUP_CONCAT(DISTINCT category ORDER BY category) as categories FROM kivi_templates;\""

echo "🎉 All done! Templates are now in the database with complete data including formulas and scoring rules."
