#!/bin/bash

# Insert All Assessment Templates Script
# This script inserts all assessment templates from frontend array into database
# Server: 195.35.45.17
# Database: kivi
# User: root
# Password: Tiger@123

echo "🚀 Starting insertion of all assessment templates into database..."

# Server credentials
SERVER="195.35.45.17"
USER="root"
PASSWORD="Tiger@123"
DATABASE="kivi"

# Function to execute SQL command
execute_sql() {
    local sql="$1"
    echo "Executing: $sql"
    sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USER@$SERVER" "mysql -u $USER -p$PASSWORD $DATABASE -e \"$sql\""
}

echo "📋 Inserting assessment templates..."

# 1. ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-PRIMARY
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-PRIMARY', 'RIPA-Primary', 'Cognitive', 'The RIPA-A quantifies & describes cognitive-linguistic deficits in individuals between the ages of 5-0 and 12-11 who face difficulties in attention, memory, orientation, language and communication, problem solving and abstract reasoning.', '🧠', '{\"id\": \"RIPA-Primary\", \"name\": \"ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-PRIMARY\", \"description\": \"The RIPA-A quantifies & describes cognitive-linguistic deficits in individuals between the ages of 5-0 and 12-11 who face difficulties in attention, memory, orientation, language and communication, problem solving and abstract reasoning.\", \"category\": \"Cognitive\", \"icon\": \"🧠\", \"subtests\": [\"Attention\", \"Memory\", \"Orientation\", \"Language\", \"Communication\", \"Problem Solving\", \"Abstract Reasoning\"]}', '{\"compositeScore\": {\"formula\": \"SUM(subtest_scores) / COUNT(subtest_scores)\", \"weights\": {\"Attention\": 0.15, \"Memory\": 0.20, \"Orientation\": 0.10, \"Language\": 0.25, \"Communication\": 0.15, \"Problem Solving\": 0.10, \"Abstract Reasoning\": 0.05}}}', '{\"ageNorms\": true, \"standardScores\": true, \"percentileRanks\": true, \"interpretationRanges\": [{\"range\": \"1-5\", \"label\": \"Severe Deficit\", \"color\": \"#dc2626\"}, {\"range\": \"6-10\", \"label\": \"Moderate Deficit\", \"color\": \"#f97316\"}, {\"range\": \"11-14\", \"label\": \"Mild Deficit\", \"color\": \"#eab308\"}, {\"range\": \"15-19\", \"label\": \"Average/Above Average\", \"color\": \"#22c55e\"}]}', '5-12 years', '[\"English\", \"Hindi\"]', 'active', 1, 1);"

# 2. ADHD-DSM5 Checklist
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('ADHD-DSM5 Checklist', 'ADHT-BSM', 'ADHD', 'DSM-5 ADHD Checklist with checkbox-based criteria selection for inattention and hyperactivity', '📋', '{\"id\": \"ADHT-BSM\", \"name\": \"ADHD-DSM5 Checklist\", \"description\": \"DSM-5 ADHD Checklist with checkbox-based criteria selection for inattention and hyperactivity\", \"category\": \"ADHD\", \"icon\": \"📋\", \"sections\": [{\"name\": \"Inattention\", \"criteria\": [\"Often fails to give close attention to details\", \"Often has difficulty sustaining attention\", \"Often does not seem to listen when spoken to directly\", \"Often does not follow through on instructions\", \"Often has difficulty organizing tasks\", \"Often avoids tasks requiring sustained mental effort\", \"Often loses things necessary for tasks\", \"Often easily distracted by extraneous stimuli\", \"Often forgetful in daily activities\"], \"requiredForDiagnosis\": 6}, {\"name\": \"Hyperactivity-Impulsivity\", \"criteria\": [\"Often fidgets with or taps hands or feet\", \"Often leaves seat in situations when remaining seated is expected\", \"Often runs about or climbs in inappropriate situations\", \"Often unable to play or engage in leisure activities quietly\", \"Often \\\"on the go\\\" or acts as if \\\"driven by a motor\\\"\", \"Often talks excessively\", \"Often blurts out an answer before question completed\", \"Often has difficulty waiting for turn\", \"Often interrupts or intrudes on others\"], \"requiredForDiagnosis\": 6}]}', '{\"inattentionScore\": {\"formula\": \"COUNT(criteria_checked)\", \"max\": 9}, \"hyperactivityScore\": {\"formula\": \"COUNT(criteria_checked)\", \"max\": 9}, \"totalScore\": {\"formula\": \"inattentionScore + hyperactivityScore\", \"max\": 18}}', '{\"diagnosticCriteria\": true, \"ageSpecific\": true, \"crossSetting\": true, \"impairmentRequired\": true, \"interpretation\": {\"0-2\": \"Unlikely ADHD\", \"3-5\": \"Possible ADHD\", \"6-9\": \"Likely ADHD\", \"10+\": \"Very Likely ADHD\"}}', '4-18 years', '[\"English\", \"Hindi\", \"Spanish\"]', 'active', 1, 2);"

# 3. Aston Index Assessment
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Aston Index Assessment', 'Aston-Index', 'Educational', 'The Aston Index procedures are designed to be used by class teachers, psychologists, and others who wish to identify children with special educational needs.', '📚', '{\"id\": \"Aston-Index\", \"name\": \"Aston Index Assessment\", \"description\": \"The Aston Index procedures are designed to be used by class teachers, psychologists, and others who wish to identify children with special educational needs.\", \"category\": \"Educational\", \"icon\": \"📚\", \"subtests\": [\"Visual Perception\", \"Auditory Perception\", \"Motor Skills\", \"Language Development\", \"Cognitive Skills\"]}', '{\"totalScore\": {\"formula\": \"SUM(subtest_scores)\", \"max\": 100}, \"percentileScore\": {\"formula\": \"(totalScore / 100) * 100\"}}', '{\"ageNorms\": true, \"standardScores\": true, \"specialEducationIdentification\": true}', '5-16 years', '[\"English\"]', 'active', 1, 3);"

# 4. WRAT5-India Blue Form
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WRAT5-India Blue Form', 'WRAT5', 'Academic', 'Wide Range Achievement Test 5 - India Blue Form for assessing reading, spelling, and math skills', '✏️', '{\"id\": \"WRAT5\", \"name\": \"WRAT5-India Blue Form\", \"description\": \"Wide Range Achievement Test 5 - India Blue Form for assessing reading, spelling, and math skills\", \"category\": \"Academic\", \"icon\": \"✏️\", \"subtests\": [\"Word Reading\", \"Sentence Comprehension\", \"Spelling\", \"Math Computation\"]}', '{\"readingRaw\": {\"formula\": \"SUM(correct_answers)\", \"max\": 55}, \"spellingRaw\": {\"formula\": \"SUM(correct_answers)\", \"max\": 42}, \"mathRaw\": {\"formula\": \"SUM(correct_answers)\", \"max\": 45}, \"compositeRaw\": {\"formula\": \"readingRaw + spellingRaw + mathRaw\"}}', '{\"standardScores\": true, \"percentileRanks\": true, \"ageEquivalents\": true, \"gradeEquivalents\": true, \"confidenceIntervals\": true}', '5-94 years', '[\"English\"]', 'active', 1, 4);"

# 5. ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-SECONDARY
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-SECONDARY', 'RIPA-Secondary', 'Cognitive', 'The RIPA-2 is a structured, criterion-referenced test that provides baseline information and can be used to identify cognitive-linguistic deficits in adolescents and adults.', '🧠', '{\"id\": \"RIPA-Secondary\", \"name\": \"ROSS INFORMATION PROCESSING ASSESSMENT (RIPA)-SECONDARY\", \"description\": \"The RIPA-2 is a structured, criterion-referenced test that provides baseline information and can be used to identify cognitive-linguistic deficits in adolescents and adults.\", \"category\": \"Cognitive\", \"icon\": \"🧠\", \"subtests\": [\"Attention\", \"Memory\", \"Orientation\", \"Language\", \"Communication\", \"Problem Solving\", \"Abstract Reasoning\"]}', '{\"compositeScore\": {\"formula\": \"SUM(subtest_scores) / COUNT(subtest_scores)\"}}', '{\"ageNorms\": true, \"standardScores\": true, \"adolescentAdultNorms\": true}', '13-21 years', '[\"English\"]', 'active', 1, 5);"

# 6. ADHD Rating Scale-4
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('ADHD Rating Scale-4', 'ADHD-Rating-4', 'ADHD', 'ADHD Rating Scale-4 for assessing attention deficit hyperactivity disorder symptoms', '📊', '{\"id\": \"ADHD-Rating-4\", \"name\": \"ADHD Rating Scale-4\", \"description\": \"ADHD Rating Scale-4 for assessing attention deficit hyperactivity disorder symptoms\", \"category\": \"ADHD\", \"icon\": \"📊\", \"subscales\": [\"Inattention\", \"Hyperactivity/Impulsivity\"]}', '{\"inattentionTScore\": {\"formula\": \"SUM(inattention_items) * 2 + 40\"}, \"hyperactivityTScore\": {\"formula\": \"SUM(hyperactivity_items) * 2 + 40\"}, \"combinedTScore\": {\"formula\": \"(inattentionTScore + hyperactivityTScore) / 2\"}}', '{\"tScores\": true, \"percentileRanks\": true, \"severityLevels\": true}', '5-18 years', '[\"English\"]', 'active', 1, 6);"

# 7. Vineland Social Maturity Scale-Indian
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Vineland Social Maturity Scale-Indian', 'VSMS-Indian', 'Social', 'Vineland Social Maturity Scale adapted for Indian population to assess social competence', '👥', '{\"id\": \"VSMS-Indian\", \"name\": \"Vineland Social Maturity Scale-Indian\", \"description\": \"Vineland Social Maturity Scale adapted for Indian population to assess social competence\", \"category\": \"Social\", \"icon\": \"👥\", \"domains\": [\"Self-Help General\", \"Self-Help Dressing\", \"Self-Help Eating\", \"Self-Help Skills\", \"Communication\", \"Socialization\", \"Occupational Skills\", \"Self-Direction\"]}', '{\"socialAge\": {\"formula\": \"SUM(domain_scores) / 12\"}, \"socialQuotient\": {\"formula\": \"(socialAge / chronologicalAge) * 100\"}}', '{\"socialAgeEquivalent\": true, \"socialQuotient\": true, \"indianNorms\": true}', '0-18 years', '[\"English\", \"Hindi\"]', 'active', 1, 7);"

# 8. Gessel Developmental Schedule
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Gessel Developmental Schedule', 'Gessel-Developmental', 'Developmental', 'Developmental assessment tool for evaluating child development milestones', '👶', '{\"id\": \"Gessel-Developmental\", \"name\": \"Gessel Developmental Schedule\", \"description\": \"Developmental assessment tool for evaluating child development milestones\", \"category\": \"Developmental\", \"icon\": \"👶\", \"areas\": [\"Motor Behavior\", \"Adaptive Behavior\", \"Language Behavior\", \"Personal-Social Behavior\"]}', '{\"developmentalQuotient\": {\"formula\": \"(developmentalAge / chronologicalAge) * 100\"}}', '{\"developmentalAge\": true, \"developmentalQuotient\": true, \"milestoneTracking\": true}', '0-6 years', '[\"English\"]', 'active', 1, 8);"

# 9. Developmental Test of Visual Perception-2
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Developmental Test of Visual Perception-2', 'DTVP-2', 'Visual', 'Assesses visual perception and visual-motor integration skills in children', '👁️', '{\"id\": \"DTVP-2\", \"name\": \"Developmental Test of Visual Perception-2\", \"description\": \"Assesses visual perception and visual-motor integration skills in children\", \"category\": \"Visual\", \"icon\": \"👁️\", \"subtests\": [\"Eye-Hand Coordination\", \"Figure-Ground\", \"Form Constancy\", \"Position in Space\", \"Spatial Relations\", \"Visual Closure\", \"Visual-Motor Speed\", \"Visual-Motor Integration\"]}', '{\"visualPerceptionIndex\": {\"formula\": \"SUM(visual_subtests) / 5\"}, \"visualMotorIndex\": {\"formula\": \"SUM(visual_motor_subtests) / 3\"}, \"generalVisualPerceptionIndex\": {\"formula\": \"(visualPerceptionIndex + visualMotorIndex) / 2\"}}', '{\"standardScores\": true, \"percentileRanks\": true, \"ageEquivalents\": true}', '4-10 years', '[\"English\"]', 'active', 1, 9);"

# 10. Bhatia Battery of Performance Tests
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Bhatia Battery of Performance Tests', 'Bhatia-Battery', 'Cognitive', 'Performance test battery for assessing cognitive abilities in Indian context', '🔋', '{\"id\": \"Bhatia-Battery\", \"name\": \"Bhatia Battery of Performance Tests\", \"description\": \"Performance test battery for assessing cognitive abilities in Indian context\", \"category\": \"Cognitive\", \"icon\": \"🔋\", \"tests\": [\"Kohs Block Design\", \"Alexander Passalong\", \"Bender-Gestalt\", \"Draw-A-Person\", \"Seguin Form Board\", \"Victoria Visual Motor Test\"]}', '{\"performanceIQ\": {\"formula\": \"SUM(test_scores) / COUNT(test_scores)\"}}', '{\"indianNorms\": true, \"performanceIQ\": true, \"nonVerbalAssessment\": true}', '8-18 years', '[\"English\", \"Hindi\"]', 'active', 1, 10);"

# 11. Malin Intelligence Scale
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Malin Intelligence Scale', 'Malin-Intelligence', 'Intelligence', 'Indian adaptation of Wechsler Intelligence Scale for Children', '🧩', '{\"id\": \"Malin-Intelligence\", \"name\": \"Malin Intelligence Scale\", \"description\": \"Indian adaptation of Wechsler Intelligence Scale for Children\", \"category\": \"Intelligence\", \"icon\": \"🧩\", \"subtests\": [\"Information\", \"Comprehension\", \"Arithmetic\", \"Similarities\", \"Vocabulary\", \"Digit Span\", \"Picture Completion\", \"Picture Arrangement\", \"Block Design\", \"Object Assembly\", \"Coding\"]}', '{\"verbalIQ\": {\"formula\": \"SUM(verbal_subtests) / 6\"}, \"performanceIQ\": {\"formula\": \"SUM(performance_subtests) / 5\"}, \"fullScaleIQ\": {\"formula\": \"(verbalIQ + performanceIQ) / 2\"}}', '{\"verbalIQ\": true, \"performanceIQ\": true, \"fullScaleIQ\": true, \"indianNorms\": true}', '6-16 years', '[\"English\", \"Hindi\"]', 'active', 1, 11);"

# 12. Draw-A-Person Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Draw-A-Person Test', 'Draw-A-Person', 'Projective', 'Projective test assessing cognitive development through drawing', '🎨', '{\"id\": \"Draw-A-Person\", \"name\": \"Draw-A-Person Test\", \"description\": \"Projective test assessing cognitive development through drawing\", \"category\": \"Projective\", \"icon\": \"🎨\", \"elements\": [\"Head\", \"Eyes\", \"Nose\", \"Mouth\", \"Body\", \"Arms\", \"Legs\", \"Fingers\", \"Clothing\", \"Accessories\"]}', '{\"developmentalAge\": {\"formula\": \"COUNT(expected_elements_present) * 0.5 + 3\"}}', '{\"developmentalAge\": true, \"projectiveInterpretation\": true, \"cognitiveAssessment\": true}', '3-15 years', '[\"English\"]', 'active', 1, 12);"

# 13. Raven Coloured Progressive Matrices
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Raven Coloured Progressive Matrices', 'Raven-Coloured', 'Intelligence', 'Non-verbal test of observational ability and clear thinking', '🔲', '{\"id\": \"Raven-Coloured\", \"name\": \"Raven Coloured Progressive Matrices\", \"description\": \"Non-verbal test of observational ability and clear thinking\", \"category\": \"Intelligence\", \"icon\": \"🔲\", \"sets\": [\"A\", \"Ab\", \"B\", \"C\", \"D\", \"E\"], \"itemsPerSet\": 12}', '{\"rawScore\": {\"formula\": \"SUM(correct_answers)\", \"max\": 36}, \"percentileRank\": {\"formula\": \"LOOKUP(rawScore, norm_table)\"}}', '{\"nonVerbalIQ\": true, \"percentileRanks\": true, \"cultureFair\": true}', '5-11 years', '[\"English\", \"Hindi\"]', 'active', 1, 13);"

# 14. Alexander Passalong Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Alexander Passalong Test', 'Alexander-Passalong', 'Motor', 'Performance test assessing spatial and motor coordination abilities', '🤲', '{\"id\": \"Alexander-Passalong\", \"name\": \"Alexander Passalong Test\", \"description\": \"Performance test assessing spatial and motor coordination abilities\", \"category\": \"Motor\", \"icon\": \"🤲\", \"trials\": 3}', '{\"averageTime\": {\"formula\": \"SUM(completion_times) / 3\"}, \"accuracyScore\": {\"formula\": \"SUM(correct_placements) / 3\"}}', '{\"motorCoordination\": true, \"spatialAbility\": true, \"timedPerformance\": true}', '8-18 years', '[\"English\"]', 'active', 1, 14);"

# 15. Differential Aptitude Tests
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Differential Aptitude Tests', 'Differential-Aptitude', 'Aptitude', 'Battery of tests measuring various aptitudes and abilities', '📏', '{\"id\": \"Differential-Aptitude\", \"name\": \"Differential Aptitude Tests\", \"description\": \"Battery of tests measuring various aptitudes and abilities\", \"category\": \"Aptitude\", \"icon\": \"📏\", \"tests\": [\"Verbal Reasoning\", \"Numerical Ability\", \"Abstract Reasoning\", \"Clerical Speed\", \"Mechanical Reasoning\", \"Space Relations\", \"Language Usage\", \"Perceptual Speed\"]}', '{\"aptitudeProfile\": {\"formula\": \"ARRAY(test_scores)\"}}', '{\"careerGuidance\": true, \"aptitudeProfile\": true, \"strengthWeaknessAnalysis\": true}', '12-18 years', '[\"English\"]', 'active', 1, 15);"

# 16. Kohs Block Design Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Kohs Block Design Test', 'Kohs-Block', 'Intelligence', 'Non-verbal intelligence test using colored blocks', '🧱', '{\"id\": \"Kohs-Block\", \"name\": \"Kohs Block Design Test\", \"description\": \"Non-verbal intelligence test using colored blocks\", \"category\": \"Intelligence\", \"icon\": \"🧱\", \"designs\": 16, \"timeLimit\": {\"perDesign\": \"2 minutes\"}}', '{\"performanceScore\": {\"formula\": \"SUM(correct_designs) + TIME_BONUS\"}, \"iqEstimate\": {\"formula\": \"LOOKUP(performanceScore, iq_table)\"}}', '{\"nonVerbalIQ\": true, \"performanceBased\": true, \"timeBonus\": true}', '8-18 years', '[\"English\"]', 'active', 1, 16);"

# 17. Raven Standard Progressive Matrices
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Raven Standard Progressive Matrices', 'Standard-Progressive', 'Intelligence', 'Advanced non-verbal test of analytical reasoning', '🔳', '{\"id\": \"Standard-Progressive\", \"name\": \"Raven Standard Progressive Matrices\", \"description\": \"Advanced non-verbal test of analytical reasoning\", \"category\": \"Intelligence\", \"icon\": \"🔳\", \"sets\": [\"A\", \"B\", \"C\", \"D\", \"E\"], \"itemsPerSet\": 12}', '{\"rawScore\": {\"formula\": \"SUM(correct_answers)\", \"max\": 60}, \"percentileRank\": {\"formula\": \"LOOKUP(rawScore, norm_table)\"}}', '{\"nonVerbalIQ\": true, \"percentileRanks\": true, \"analyticalReasoning\": true}', '6-65 years', '[\"English\"]', 'active', 1, 17);"

# 18. Bender Gestalt Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Bender Gestalt Test', 'Bender-Gestalt', 'Visual-Motor', 'Visual-motor gestalt test assessing neurological functioning', '🌀', '{\"id\": \"Bender-Gestalt\", \"name\": \"Bender Gestalt Test\", \"description\": \"Visual-motor gestalt test assessing neurological functioning\", \"category\": \"Visual-Motor\", \"icon\": \"🌀\", \"figures\": 9}', '{\"developmentalLevel\": {\"formula\": \"COUNT(devotional_errors) + COUNT(rotation_errors)\"}}', '{\"neurologicalScreening\": true, \"developmentalAssessment\": true, \"visualMotorIntegration\": true}', '5-11 years', '[\"English\"]', 'active', 1, 18);"

# 19. Goodenough Harris Draw-A-Man Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Goodenough Harris Draw-A-Man Test', 'Goodenough-Harris', 'Projective', 'Drawing test assessing intellectual development', '👤', '{\"id\": \"Goodenough-Harris\", \"name\": \"Goodenough Harris Draw-A-Man Test\", \"description\": \"Drawing test assessing intellectual development\", \"category\": \"Projective\", \"icon\": \"👤\", \"elements\": [\"Head\", \"Eyes\", \"Nose\", \"Mouth\", \"Hair\", \"Body\", \"Arms\", \"Legs\", \"Joints\", \"Clothing\"]}', '{\"mentalAge\": {\"formula\": \"COUNT(elements_present) * 0.8 + 3\"}}', '{\"mentalAge\": true, \"projectiveInterpretation\": true, \"intellectualAssessment\": true}', '3-15 years', '[\"English\"]', 'active', 1, 19);"

# 20. Seguin Form Board Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Seguin Form Board Test', 'Seguin-Form', 'Motor', 'Performance test assessing form discrimination and motor skills', '🔷', '{\"id\": \"Seguin-Form\", \"name\": \"Seguin Form Board Test\", \"description\": \"Performance test assessing form discrimination and motor skills\", \"category\": \"Motor\", \"icon\": \"🔷\", \"forms\": 10}', '{\"performanceScore\": {\"formula\": \"SUM(correct_placements) + TIME_BONUS\"}}', '{\"formDiscrimination\": true, \"motorSkills\": true, \"timedPerformance\": true}', '8-18 years', '[\"English\"]', 'active', 1, 20);"

# 21. Victoria Visual Motor Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Victoria Visual Motor Test', 'Victoria-Visual', 'Visual-Motor', 'Assesses visual-motor integration and coordination', '👀', '{\"id\": \"Victoria-Visual\", \"name\": \"Victoria Visual Motor Test\", \"description\": \"Assesses visual-motor integration and coordination\", \"category\": \"Visual-Motor\", \"icon\": \"👀\", \"items\": 27}', '{\"vmiScore\": {\"formula\": \"SUM(correct_copies)\", \"max\": 27}}', '{\"visualMotorIntegration\": true, \"coordinationAssessment\": true}', '4-18 years', '[\"English\"]', 'active', 1, 21);"

# 22. P.G.I. Memory Scale
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('P.G.I. Memory Scale', 'Memory-Scale', 'Memory', 'Memory assessment scale for various memory functions', '🧠', '{\"id\": \"Memory-Scale\", \"name\": \"P.G.I. Memory Scale\", \"description\": \"Memory assessment scale for various memory functions\", \"category\": \"Memory\", \"icon\": \"🧠\", \"subtests\": [\"Remote Memory\", \"Recent Memory\", \"Retention of Paired Associates\", \"Recognition\", \"Immediate Memory\", \"Delayed Recall\"]}', '{\"memoryQuotient\": {\"formula\": \"SUM(subtest_scores) / COUNT(subtests)\"}}', '{\"memoryAssessment\": true, \"quotientScore\": true, \"multipleMemoryTypes\": true}', '8-60 years', '[\"English\"]', 'active', 1, 22);"

# 23. NIMHANS Brain Dysfunction Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('NIMHANS Brain Dysfunction Test', 'NIMHANS-Brain', 'Neuropsychological', 'Comprehensive neuropsychological assessment battery', '🧬', '{\"id\": \"NIMHANS-Brain\", \"name\": \"NIMHANS Brain Dysfunction Test\", \"description\": \"Comprehensive neuropsychological assessment battery\", \"category\": \"Neuropsychological\", \"icon\": \"🧬\", \"functions\": [\"Attention\", \"Memory\", \"Executive Function\", \"Language\", \"Visuospatial\", \"Motor\"]}', '{\"brainIndex\": {\"formula\": \"SUM(function_scores) / COUNT(function_scores)\"}}', '{\"neuropsychological\": true, \"comprehensiveBattery\": true, \"indianNorms\": true}', '16-60 years', '[\"English\"]', 'active', 1, 23);"

# 24. Comprehensive Language Assessment
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Comprehensive Language Assessment', 'Comprehensive-Language', 'Language', 'Comprehensive battery of tests for diagnosing language difficulties in children', '🗣️', '{\"id\": \"Comprehensive-Language\", \"name\": \"Comprehensive Language Assessment\", \"description\": \"Comprehensive battery of tests for diagnosing language difficulties in children\", \"category\": \"Language\", \"icon\": \"🗣️\", \"domains\": [\"Receptive Language\", \"Expressive Language\", \"Pragmatics\", \"Phonology\", \"Syntax\", \"Semantics\"]}', '{\"languageQuotient\": {\"formula\": \"SUM(domain_scores) / COUNT(domain_scores)\"}}', '{\"languageAssessment\": true, \"comprehensiveBattery\": true, \"multipleDomains\": true}', '3-18 years', '[\"English\"]', 'active', 1, 24);"

# 25. EACA AUTISM ASSESSMENT
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('EACA AUTISM ASSESSMENT', 'ADHDT2', 'ADHD', 'Attention-Deficit/Hyperactivity Disorder Test-Second Edition with comprehensive scoring', '📝', '{\"id\": \"ADHDT2\", \"name\": \"EACA AUTISM ASSESSMENT\", \"description\": \"Attention-Deficit/Hyperactivity Disorder Test-Second Edition with comprehensive scoring\", \"category\": \"ADHD\", \"icon\": \"📝\"}', '{\"adhdIndex\": {\"formula\": \"(inattentionScore + hyperactivityScore) / 2\"}}', '{\"comprehensiveScoring\": true, \"adhdAssessment\": true}', '6-18 years', '[\"English\"]', 'active', 1, 25);"

# 26. Bender Gestalt Test (BKT)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Bender Gestalt Test (BKT)', 'BKT', 'Motor', 'Motor coordination and kinesthetic perception assessment', '✏️', '{\"id\": \"BKT\", \"name\": \"Bender Gestalt Test (BKT)\", \"description\": \"Motor coordination and kinesthetic perception assessment\", \"category\": \"Motor\", \"icon\": \"✏️\", \"figures\": 9}', '{\"motorScore\": {\"formula\": \"SUM(accuracy_scores)\"}}', '{\"motorCoordination\": true, \"kinestheticPerception\": true}', '5-11 years', '[\"English\"]', 'active', 1, 26);"

# 27. Raven's Coloured Progressive Matrices
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Raven\\'s Coloured Progressive Matrices', 'Ravens-CPM', 'Cognitive', 'Non-verbal assessment of eductive ability and problem-solving skills', '🧩', '{\"id\": \"Ravens-CPM\", \"name\": \"Raven\\'s Coloured Progressive Matrices\", \"description\": \"Non-verbal assessment of eductive ability and problem-solving skills\", \"category\": \"Cognitive\", \"icon\": \"🧩\", \"sets\": [\"A\", \"Ab\", \"B\", \"C\", \"D\", \"E\"], \"itemsPerSet\": 12}', '{\"educativeAbility\": {\"formula\": \"SUM(correct_answers)\", \"max\": 36}}', '{\"nonVerbalReasoning\": true, \"problemSolving\": true}', '5-11 years', '[\"English\"]', 'active', 1, 27);"

# 28. Gilliam Autism Rating Scale - 3
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Gilliam Autism Rating Scale - 3', 'GARS-3', 'Autism', 'Comprehensive assessment tool for identifying autism spectrum disorders', '🧩', '{\"id\": \"GARS-3\", \"name\": \"Gilliam Autism Rating Scale - 3\", \"description\": \"Comprehensive assessment tool for identifying autism spectrum disorders\", \"category\": \"Autism\", \"icon\": \"🧩\", \"subscales\": [\"Stereotyped Behaviors\", \"Communication\", \"Social Interaction\", \"Developmental Disturbances\"]}', '{\"autismIndex\": {\"formula\": \"SUM(subscale_scores)\"}}', '{\"autismAssessment\": true, \"comprehensiveRating\": true}', '3-22 years', '[\"English\"]', 'active', 1, 28);"

# 29. Brown Executive Function/Attention Scales
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Brown Executive Function/Attention Scales', 'Brown-EF-A', 'Executive', 'Comprehensive assessment of executive function and attention processes', '🧠', '{\"id\": \"Brown-EF-A\", \"name\": \"Brown Executive Function/Attention Scales\", \"description\": \"Comprehensive assessment of executive function and attention processes\", \"category\": \"Executive\", \"icon\": \"🧠\", \"clusters\": [\"Activation\", \"Focus\", \"Effort\", \"Emotion\", \"Memory\", \"Action\"]}', '{\"executiveFunctionIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"executiveFunction\": true, \"attentionAssessment\": true}', '3-18 years', '[\"English\"]', 'active', 1, 29);"

# 30. Early Academic Competency Assessment
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Early Academic Competency Assessment', 'EACA', 'Academic', 'Comprehensive screening tool for early academic skills and school readiness', '📚', '{\"id\": \"EACA\", \"name\": \"Early Academic Competency Assessment\", \"description\": \"Comprehensive screening tool for early academic skills and school readiness\", \"category\": \"Academic\", \"icon\": \"📚\", \"domains\": [\"Pre-Reading\", \"Pre-Writing\", \"Mathematics\", \"Language\", \"Social Skills\"]}', '{\"readinessIndex\": {\"formula\": \"SUM(domain_scores)\"}}', '{\"schoolReadiness\": true, \"earlyAcademic\": true}', '4-6 years', '[\"English\"]', 'active', 1, 30);"

# 31. Educational Assessment of Children with Autism (EACA)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Educational Assessment of Children with Autism (EACA)', 'EACA-Autism', 'Autism', 'Comprehensive assessment of children with autism focusing on the triad of impairments across 7 domains', '🧩', '{\"id\": \"EACA-Autism\", \"name\": \"Educational Assessment of Children with Autism (EACA)\", \"description\": \"Comprehensive assessment of children with autism focusing on the triad of impairments across 7 domains\", \"category\": \"Autism\", \"icon\": \"🧩\", \"domains\": [\"Social Interaction\", \"Communication\", \"Imagination\", \"Behavior\", \"Cognition\", \"Sensory\", \"Motor\"]}', '{\"autismSeverity\": {\"formula\": \"SUM(domain_scores)\"}}', '{\"autismAssessment\": true, \"educationalFocus\": true}', '3-18 years', '[\"English\"]', 'active', 1, 31);"

# 32. Nelson-Denny Reading Test
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('Nelson-Denny Reading Test', 'Nelson-Denny', 'Reading', 'Comprehensive assessment of reading comprehension, vocabulary, and reading rate', '📖', '{\"id\": \"Nelson-Denny\", \"name\": \"Nelson-Denny Reading Test\", \"description\": \"Comprehensive assessment of reading comprehension, vocabulary, and reading rate\", \"category\": \"Reading\", \"icon\": \"📖\", \"subtests\": [\"Vocabulary\", \"Comprehension\", \"Reading Rate\"]}', '{\"readingIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"readingAssessment\": true, \"comprehensiveBattery\": true}', '9-18 years', '[\"English\"]', 'active', 1, 32);"

# 33. TEST OF AUDITORY PROCESSING SKILLS-TAPS-3
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('TEST OF AUDITORY PROCESSING SKILLS-TAPS-3', 'TAPS-3', 'Auditory', 'Comprehensive auditory processing assessment for phonological skills, memory abilities, and auditory cohesion', '👂', '{\"id\": \"TAPS-3\", \"name\": \"TEST OF AUDITORY PROCESSING SKILLS-TAPS-3\", \"description\": \"Comprehensive auditory processing assessment for phonological skills, memory abilities, and auditory cohesion\", \"category\": \"Auditory\", \"icon\": \"👂\", \"subtests\": [\"Phonological Awareness\", \"Phonemic Awareness\", \"Memory\", \"Cohesion\"]}', '{\"auditoryProcessingIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"auditoryProcessing\": true, \"phonologicalSkills\": true}', '4-18 years', '[\"English\"]', 'active', 1, 33);"

# 34. TEST OF WRITTEN LANGUAGE (TOWL-4)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('TEST OF WRITTEN LANGUAGE (TOWL-4)', 'TOWL-4', 'Writing', 'The TOWL-4 is a norm-referenced, reliable, and valid test of written language measuring seven skill areas and three composite scores.', '✍️', '{\"id\": \"TOWL-4\", \"name\": \"TEST OF WRITTEN LANGUAGE (TOWL-4)\", \"description\": \"The TOWL-4 is a norm-referenced, reliable, and valid test of written language measuring seven skill areas and three composite scores.\", \"category\": \"Writing\", \"icon\": \"✍️\", \"subtests\": [\"Vocabulary\", \"Spelling\", \"Punctuation\", \"Logical Sentences\", \"Sentence Combining\", \"Paragraph Writing\"]}', '{\"writtenLanguageIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"writingAssessment\": true, \"normReferenced\": true}', '9-18 years', '[\"English\"]', 'active', 1, 34);"

# 35. VINELAND ADAPTIVE BEHAVIOUR SCALES-VABS-3
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('VINELAND ADAPTIVE BEHAVIOUR SCALES-VABS-3', 'VABS-3', 'Behavior', 'Individual assessment of adaptive behaviour measuring day-to-day activities necessary for self-care and social interaction.', '👥', '{\"id\": \"VABS-3\", \"name\": \"VINELAND ADAPTIVE BEHAVIOUR SCALES-VABS-3\", \"description\": \"Individual assessment of adaptive behaviour measuring day-to-day activities necessary for self-care and social interaction.\", \"category\": \"Behavior\", \"icon\": \"👥\", \"domains\": [\"Communication\", \"Daily Living Skills\", \"Socialization\", \"Motor Skills\", \"Adaptive Behavior\"]}', '{\"adaptiveBehaviorIndex\": {\"formula\": \"SUM(domain_scores)\"}}', '{\"adaptiveBehavior\": true, \"dailyLiving\": true}', '0-90 years', '[\"English\"]', 'active', 1, 35);"

# 36. WECHSLER'S INTELLIGENCE SCALE FOR CHILDREN -WISC-IV India
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WECHSLER\\'S INTELLIGENCE SCALE FOR CHILDREN -WISC-IV India', 'WISC-4', 'Intelligence', 'Norm-referenced, individually administered test of intelligence for children with verbal and performance subtests.', '🧠', '{\"id\": \"WISC-4\", \"name\": \"WECHSLER\\'S INTELLIGENCE SCALE FOR CHILDREN -WISC-IV India\", \"description\": \"Norm-referenced, individually administered test of intelligence for children with verbal and performance subtests.\", \"category\": \"Intelligence\", \"icon\": \"🧠\", \"subtests\": [\"Similarities\", \"Vocabulary\", \"Comprehension\", \"Information\", \"Word Reasoning\", \"Digit Span\", \"Letter-Number Sequencing\", \"Coding\", \"Symbol Search\", \"Block Design\", \"Picture Concepts\", \"Matrix Reasoning\"]}', '{\"verbalComprehension\": {\"formula\": \"SUM(verbal_subtests) / 5\"}, \"perceptualReasoning\": {\"formula\": \"SUM(perceptual_subtests) / 3\"}, \"workingMemory\": {\"formula\": \"SUM(working_memory_subtests) / 2\"}, \"processingSpeed\": {\"formula\": \"SUM(processing_speed_subtests) / 2\"}, \"fullScaleIQ\": {\"formula\": \"(verbalComprehension + perceptualReasoning + workingMemory + processingSpeed) / 4\"}}', '{\"intelligenceAssessment\": true, \"indianNorms\": true, \"comprehensiveBattery\": true}', '6-16 years', '[\"English\"]', 'active', 1, 36);"

# 37. WJ-III - TESTS OF ACHIEVEMENT FORM C/ BRIEF BATTERY
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WJ-III - TESTS OF ACHIEVEMENT FORM C/ BRIEF BATTERY', 'WJ-3', 'Achievement', 'Norm-referenced individually administered tests measuring academic achievement across reading, math, and writing.', '📊', '{\"id\": \"WJ-3\", \"name\": \"WJ-III - TESTS OF ACHIEVEMENT FORM C/ BRIEF BATTERY\", \"description\": \"Norm-referenced individually administered tests measuring academic achievement across reading, math, and writing.\", \"category\": \"Achievement\", \"icon\": \"📊\", \"clusters\": [\"Broad Reading\", \"Broad Math\", \"Broad Written Language\", \"Oral Expression\", \"Listening Comprehension\"]}', '{\"achievementIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"academicAchievement\": true, \"normReferenced\": true}', '2-90 years', '[\"English\"]', 'active', 1, 37);"

# 38. WOODCOCK-JOHNSON TESTS OF COGNITIVE ABILITIES IV (WJ-Cog)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WOODCOCK-JOHNSON TESTS OF COGNITIVE ABILITIES IV (WJ-Cog)', 'WJ-Cog', 'Cognitive', '18 tests measuring different aspects of cognitive ability based on CHC theory, with cluster scores for interpretative purposes.', '🧠', '{\"id\": \"WJ-Cog\", \"name\": \"WOODCOCK-JOHNSON TESTS OF COGNITIVE ABILITIES IV (WJ-Cog)\", \"description\": \"18 tests measuring different aspects of cognitive ability based on CHC theory, with cluster scores for interpretative purposes.\", \"category\": \"Cognitive\", \"icon\": \"🧠\", \"clusters\": [\"Comprehension-Knowledge\", \"Long-Term Retrieval\", \"Visual-Spatial Thinking\", \"Auditory Processing\", \"Processing Speed\", \"Short-Term Memory\", \"Fluid Reasoning\", \"Quantitative Reasoning\"]}', '{\"cognitiveIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"cognitiveAbilities\": true, \"CHCTheory\": true}', '2-90 years', '[\"English\"]', 'active', 1, 38);"

# 39. WOODCOCK JOHNSON IV TESTS OF ACHIEVEMENT (WJ-Ach)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WOODCOCK JOHNSON IV TESTS OF ACHIEVEMENT (WJ-Ach)', 'WJ-Ach', 'Achievement', 'Comprehensive set of individually administered tests to measure educational achievement in reading, mathematics, written language, and academic skills.', '📚', '{\"id\": \"WJ-Ach\", \"name\": \"WOODCOCK JOHNSON IV TESTS OF ACHIEVEMENT (WJ-Ach)\", \"description\": \"Comprehensive set of individually administered tests to measure educational achievement in reading, mathematics, written language, and academic skills.\", \"category\": \"Achievement\", \"icon\": \"📚\", \"clusters\": [\"Basic Reading Skills\", \"Reading Comprehension\", \"Broad Reading\", \"Math Calculation Skills\", \"Math Problem Solving\", \"Broad Mathematics\", \"Written Expression\", \"Broad Written Language\"]}', '{\"achievementIndex\": {\"formula\": \"SUM(cluster_scores)\"}}', '{\"academicAchievement\": true, \"comprehensiveBattery\": true}', '2-90 years', '[\"English\"]', 'active', 1, 39);"

# 40. WIDE RANGE ACHIEVEMENT TEST- WRAT-5 (ENGLISH)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WIDE RANGE ACHIEVEMENT TEST- WRAT-5 (ENGLISH)', 'WRAT5', 'Achievement', 'Norm-referenced test measuring basic academic skills of word reading, sentence comprehension, spelling, and math computation.', '📝', '{\"id\": \"WRAT5\", \"name\": \"WIDE RANGE ACHIEVEMENT TEST- WRAT-5 (ENGLISH)\", \"description\": \"Norm-referenced test measuring basic academic skills of word reading, sentence comprehension, spelling, and math computation.\", \"category\": \"Achievement\", \"icon\": \"📝\", \"subtests\": [\"Word Reading\", \"Sentence Comprehension\", \"Spelling\", \"Math Computation\"]}', '{\"basicSkillsIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"basicAcademicSkills\": true, \"normReferenced\": true}', '5-94 years', '[\"English\"]', 'active', 1, 40);"

# 41. WOODCOCK READING MASTERY TESTS-II (WRMT-II)
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('WOODCOCK READING MASTERY TESTS-II (WRMT-II)', 'WRMT2', 'Reading', 'Individually administered, timed tests measuring Basic Skills, Reading Comprehension, Oral Reading Fluency and Listening Comprehension.', '📖', '{\"id\": \"WRMT2\", \"name\": \"WOODCOCK READING MASTERY TESTS-II (WRMT-II)\", \"description\": \"Individually administered, timed tests measuring Basic Skills, Reading Comprehension, Oral Reading Fluency and Listening Comprehension.\", \"category\": \"Reading\", \"icon\": \"📖\", \"subtests\": [\"Visual-Auditory Learning\", \"Letter Identification\", \"Word Identification\", \"Word Attack\", \"Word Comprehension\", \"Passage Comprehension\", \"Oral Reading Fluency\"]}', '{\"readingMasteryIndex\": {\"formula\": \"SUM(subtest_scores)\"}}', '{\"readingMastery\": true, \"timedTests\": true}', '5-75 years', '[\"English\"]', 'active', 1, 41);"

# 42. DIAGNOSTIC ASSESSMENT REPORT
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('DIAGNOSTIC ASSESSMENT REPORT', 'DiagnosticReport', 'Diagnostic', 'Comprehensive diagnostic assessment report based on DSM-5 criteria and standardized test results.', '🧠', '{\"id\": \"DiagnosticReport\", \"name\": \"DIAGNOSTIC ASSESSMENT REPORT\", \"description\": \"Comprehensive diagnostic assessment report based on DSM-5 criteria and standardized test results.\", \"category\": \"Diagnostic\", \"icon\": \"🧠\", \"sections\": [\"Client Information\", \"Background History\", \"Assessment Results\", \"Diagnostic Impressions\", \"Recommendations\", \"Prognosis\"]}', '{\"diagnosticSummary\": {\"formula\": \"CONCATENATE(assessment_results, diagnostic_impressions)\"}}', '{\"diagnosticReport\": true, \"dsm5Criteria\": true}', 'All ages', '[\"English\"]', 'active', 1, 42);"

# 43. SUMMARY OF EVALUATION
execute_sql "INSERT INTO kivi_templates (name, type, category, description, icon, template_data, formula_config, scoring_rules, age_range, languages, status, is_active, sort_order) VALUES ('SUMMARY OF EVALUATION', 'EvaluationSummary', 'Summary', 'Comprehensive summary of evaluation results across multiple assessment instruments including WJ-IV COG, WJ-IV ACH, and Brown\\'s EF/A Scale.', '📊', '{\"id\": \"EvaluationSummary\", \"name\": \"SUMMARY OF EVALUATION\", \"description\": \"Comprehensive summary of evaluation results across multiple assessment instruments including WJ-IV COG, WJ-IV ACH, and Brown\\'s EF/A Scale.\", \"category\": \"Summary\", \"icon\": \"📊\", \"instruments\": [\"WJ-IV COG\", \"WJ-IV ACH\", \"Brown EF/A Scale\"]}', '{\"evaluationSummary\": {\"formula\": \"AGGREGATE(instrument_results)\"}}', '{\"comprehensiveSummary\": true, \"multiInstrument\": true}', 'All ages', '[\"English\"]', 'active', 1, 43);"

echo "✅ All assessment templates have been successfully inserted into the database!"

# Show summary
echo "📊 Summary of inserted templates:"
sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USER@$SERVER" "mysql -u $USER -p$PASSWORD $DATABASE -e \"SELECT COUNT(*) as total_templates, COUNT(CASE WHEN is_active = 1 THEN 1 END) as active_templates, GROUP_CONCAT(DISTINCT category ORDER BY category) as categories FROM kivi_templates WHERE type IN ('RIPA-Primary', 'ADHT-BSM', 'Aston-Index', 'WRAT5', 'RIPA-Secondary', 'ADHD-Rating-4', 'VSMS-Indian', 'Gessel-Developmental', 'DTVP-2', 'Bhatia-Battery', 'Malin-Intelligence', 'Draw-A-Person', 'Raven-Coloured', 'Alexander-Passalong', 'Differential-Aptitude', 'Kohs-Block', 'Standard-Progressive', 'Bender-Gestalt', 'Goodenough-Harris', 'Seguin-Form', 'Victoria-Visual', 'Memory-Scale', 'NIMHANS-Brain', 'Comprehensive-Language', 'ADHDT2', 'BKT', 'Ravens-CPM', 'GARS-3', 'Brown-EF-A', 'EACA', 'EACA-Autism', 'Nelson-Denny', 'TAPS-3', 'TOWL-4', 'VABS-3', 'WISC-4', 'WJ-3', 'WJ-Cog', 'WJ-Ach', 'WRAT5', 'WRMT2', 'DiagnosticReport', 'EvaluationSummary');\""

echo "🎉 Template insertion completed successfully!"
echo "📋 Total templates inserted: 43"
echo "🔄 All templates include formulas, scoring rules, and complete data"
echo "🗄️ Database: kivi"
echo "🌐 Server: $SERVER"
